// Code generated by pigeon; DO NOT EDIT.

package pegparser

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"
)

type Object map[string]interface{}

func newObject() Object {
	return make(Object)
}

func merge_obj(obj Object, secondObj Object) Object {
	if obj == nil {
		return secondObj
	}

	for k, v := range secondObj {
		if _, ok := obj[k]; !ok {
			obj[k] = v
		}
	}

	return obj
}

func toIfaceSlice(v interface{}) []interface{} {
	if v == nil {
		return nil
	}
	return v.([]interface{})
}

func charsToString(v interface{}) string {
	if v == nil {
		return ""
	}

	result := make([]string, len(v.([]interface{})))
	for i, v := range v.([]interface{}) {
		result[i] = string(v.([]uint8))
	}

	return strings.Join(result, "")
}


func CharsToString(v interface{}) string {
	return charsToString(v)
}

var g = &grammar{
	rules: []*rule{
		{
			name: "Project",
			pos:  position{line: 56, col: 1, offset: 1066},
			expr: &actionExpr{
				pos: position{line: 56, col: 12, offset: 1077},
				run: (*parser).callonProject1,
				expr: &seqExpr{
					pos: position{line: 56, col: 12, offset: 1077},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 56, col: 12, offset: 1077},
							label: "headComment",
							expr: &zeroOrOneExpr{
								pos: position{line: 56, col: 24, offset: 1089},
								expr: &ruleRefExpr{
									pos:  position{line: 56, col: 24, offset: 1089},
									name: "SingleLineComment",
								},
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 56, col: 43, offset: 1108},
							expr: &ruleRefExpr{
								pos:  position{line: 56, col: 43, offset: 1108},
								name: "InlineComment",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 56, col: 58, offset: 1123},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 56, col: 60, offset: 1125},
							label: "obj",
							expr: &ruleRefExpr{
								pos:  position{line: 56, col: 64, offset: 1129},
								name: "Object",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 56, col: 71, offset: 1136},
							name: "NewLine",
						},
						&ruleRefExpr{
							pos:  position{line: 56, col: 79, offset: 1144},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "Object",
			pos:  position{line: 67, col: 1, offset: 1326},
			expr: &actionExpr{
				pos: position{line: 67, col: 11, offset: 1336},
				run: (*parser).callonObject1,
				expr: &seqExpr{
					pos: position{line: 67, col: 11, offset: 1336},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 67, col: 11, offset: 1336},
							val:        "{",
							ignoreCase: false,
							want:       "\"{\"",
						},
						&labeledExpr{
							pos:   position{line: 67, col: 15, offset: 1340},
							label: "obj",
							expr: &choiceExpr{
								pos: position{line: 67, col: 20, offset: 1345},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 67, col: 20, offset: 1345},
										name: "AssignmentList",
									},
									&ruleRefExpr{
										pos:  position{line: 67, col: 37, offset: 1362},
										name: "EmptyBody",
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 67, col: 48, offset: 1373},
							val:        "}",
							ignoreCase: false,
							want:       "\"}\"",
						},
					},
				},
			},
		},
		{
			name: "EmptyBody",
			pos:  position{line: 71, col: 1, offset: 1406},
			expr: &actionExpr{
				pos: position{line: 71, col: 14, offset: 1419},
				run: (*parser).callonEmptyBody1,
				expr: &ruleRefExpr{
					pos:  position{line: 71, col: 14, offset: 1419},
					name: "_",
				},
			},
		},
		{
			name: "AssignmentList",
			pos:  position{line: 75, col: 1, offset: 1458},
			expr: &actionExpr{
				pos: position{line: 75, col: 19, offset: 1476},
				run: (*parser).callonAssignmentList1,
				expr: &seqExpr{
					pos: position{line: 75, col: 19, offset: 1476},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 75, col: 19, offset: 1476},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 75, col: 21, offset: 1478},
							label: "_list",
							expr: &oneOrMoreExpr{
								pos: position{line: 75, col: 27, offset: 1484},
								expr: &seqExpr{
									pos: position{line: 75, col: 28, offset: 1485},
									exprs: []interface{}{
										&choiceExpr{
											pos: position{line: 75, col: 29, offset: 1486},
											alternatives: []interface{}{
												&labeledExpr{
													pos:   position{line: 75, col: 29, offset: 1486},
													label: "a",
													expr: &ruleRefExpr{
														pos:  position{line: 75, col: 31, offset: 1488},
														name: "Assignment",
													},
												},
												&labeledExpr{
													pos:   position{line: 75, col: 44, offset: 1501},
													label: "d",
													expr: &ruleRefExpr{
														pos:  position{line: 75, col: 46, offset: 1503},
														name: "DelimitedSection",
													},
												},
											},
										},
										&ruleRefExpr{
											pos:  position{line: 75, col: 64, offset: 1521},
											name: "_",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Assignment",
			pos:  position{line: 87, col: 1, offset: 1803},
			expr: &choiceExpr{
				pos: position{line: 87, col: 15, offset: 1817},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 87, col: 15, offset: 1817},
						name: "SimpleAssignment",
					},
					&ruleRefExpr{
						pos:  position{line: 87, col: 34, offset: 1836},
						name: "CommentedAssignment",
					},
				},
			},
		},
		{
			name: "SimpleAssignment",
			pos:  position{line: 89, col: 1, offset: 1859},
			expr: &actionExpr{
				pos: position{line: 89, col: 21, offset: 1879},
				run: (*parser).callonSimpleAssignment1,
				expr: &seqExpr{
					pos: position{line: 89, col: 21, offset: 1879},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 89, col: 21, offset: 1879},
							label: "id",
							expr: &ruleRefExpr{
								pos:  position{line: 89, col: 24, offset: 1882},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 89, col: 35, offset: 1893},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 89, col: 37, offset: 1895},
							val:        "=",
							ignoreCase: false,
							want:       "\"=\"",
						},
						&ruleRefExpr{
							pos:  position{line: 89, col: 41, offset: 1899},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 89, col: 43, offset: 1901},
							label: "val",
							expr: &ruleRefExpr{
								pos:  position{line: 89, col: 47, offset: 1905},
								name: "Value",
							},
						},
						&litMatcher{
							pos:        position{line: 89, col: 53, offset: 1911},
							val:        ";",
							ignoreCase: false,
							want:       "\";\"",
						},
					},
				},
			},
		},
		{
			name: "CommentedAssignment",
			pos:  position{line: 95, col: 1, offset: 2006},
			expr: &choiceExpr{
				pos: position{line: 95, col: 24, offset: 2029},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 95, col: 24, offset: 2029},
						name: "CommentedAssignment1",
					},
					&ruleRefExpr{
						pos:  position{line: 95, col: 47, offset: 2052},
						name: "CommentedAssignment2",
					},
				},
			},
		},
		{
			name: "CommentedAssignment1",
			pos:  position{line: 97, col: 1, offset: 2076},
			expr: &actionExpr{
				pos: position{line: 97, col: 25, offset: 2100},
				run: (*parser).callonCommentedAssignment11,
				expr: &seqExpr{
					pos: position{line: 97, col: 25, offset: 2100},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 97, col: 25, offset: 2100},
							label: "commentedId",
							expr: &ruleRefExpr{
								pos:  position{line: 97, col: 37, offset: 2112},
								name: "CommentedIdentifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 97, col: 57, offset: 2132},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 97, col: 59, offset: 2134},
							val:        "=",
							ignoreCase: false,
							want:       "\"=\"",
						},
						&ruleRefExpr{
							pos:  position{line: 97, col: 63, offset: 2138},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 97, col: 65, offset: 2140},
							label: "val",
							expr: &ruleRefExpr{
								pos:  position{line: 97, col: 69, offset: 2144},
								name: "Value",
							},
						},
						&litMatcher{
							pos:        position{line: 97, col: 75, offset: 2150},
							val:        ";",
							ignoreCase: false,
							want:       "\";\"",
						},
					},
				},
			},
		},
		{
			name: "CommentedAssignment2",
			pos:  position{line: 106, col: 1, offset: 2400},
			expr: &actionExpr{
				pos: position{line: 106, col: 25, offset: 2424},
				run: (*parser).callonCommentedAssignment21,
				expr: &seqExpr{
					pos: position{line: 106, col: 25, offset: 2424},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 106, col: 25, offset: 2424},
							label: "id",
							expr: &ruleRefExpr{
								pos:  position{line: 106, col: 28, offset: 2427},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 106, col: 39, offset: 2438},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 106, col: 41, offset: 2440},
							val:        "=",
							ignoreCase: false,
							want:       "\"=\"",
						},
						&ruleRefExpr{
							pos:  position{line: 106, col: 45, offset: 2444},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 106, col: 47, offset: 2446},
							label: "commentedVal",
							expr: &ruleRefExpr{
								pos:  position{line: 106, col: 60, offset: 2459},
								name: "CommentedValue",
							},
						},
						&litMatcher{
							pos:        position{line: 106, col: 75, offset: 2474},
							val:        ";",
							ignoreCase: false,
							want:       "\";\"",
						},
					},
				},
			},
		},
		{
			name: "CommentedIdentifier",
			pos:  position{line: 113, col: 1, offset: 2668},
			expr: &actionExpr{
				pos: position{line: 113, col: 24, offset: 2691},
				run: (*parser).callonCommentedIdentifier1,
				expr: &seqExpr{
					pos: position{line: 113, col: 24, offset: 2691},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 113, col: 24, offset: 2691},
							label: "id",
							expr: &ruleRefExpr{
								pos:  position{line: 113, col: 27, offset: 2694},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 113, col: 38, offset: 2705},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 113, col: 40, offset: 2707},
							label: "comment",
							expr: &ruleRefExpr{
								pos:  position{line: 113, col: 48, offset: 2715},
								name: "InlineComment",
							},
						},
					},
				},
			},
		},
		{
			name: "CommentedValue",
			pos:  position{line: 120, col: 1, offset: 2887},
			expr: &actionExpr{
				pos: position{line: 120, col: 19, offset: 2905},
				run: (*parser).callonCommentedValue1,
				expr: &seqExpr{
					pos: position{line: 120, col: 19, offset: 2905},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 120, col: 19, offset: 2905},
							label: "literal",
							expr: &ruleRefExpr{
								pos:  position{line: 120, col: 27, offset: 2913},
								name: "Value",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 120, col: 33, offset: 2919},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 120, col: 35, offset: 2921},
							label: "comment",
							expr: &ruleRefExpr{
								pos:  position{line: 120, col: 43, offset: 2929},
								name: "InlineComment",
							},
						},
					},
				},
			},
		},
		{
			name: "InlineComment",
			pos:  position{line: 127, col: 1, offset: 3122},
			expr: &actionExpr{
				pos: position{line: 127, col: 18, offset: 3139},
				run: (*parser).callonInlineComment1,
				expr: &seqExpr{
					pos: position{line: 127, col: 18, offset: 3139},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 127, col: 18, offset: 3139},
							name: "InlineCommentOpen",
						},
						&labeledExpr{
							pos:   position{line: 127, col: 36, offset: 3157},
							label: "body",
							expr: &oneOrMoreExpr{
								pos: position{line: 127, col: 41, offset: 3162},
								expr: &charClassMatcher{
									pos:        position{line: 127, col: 41, offset: 3162},
									val:        "[^*]",
									chars:      []rune{'*'},
									ignoreCase: false,
									inverted:   true,
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 127, col: 47, offset: 3168},
							name: "InlineCommentClose",
						},
					},
				},
			},
		},
		{
			name: "InlineCommentOpen",
			pos:  position{line: 131, col: 1, offset: 3232},
			expr: &litMatcher{
				pos:        position{line: 131, col: 22, offset: 3253},
				val:        "/*",
				ignoreCase: false,
				want:       "\"/*\"",
			},
		},
		{
			name: "InlineCommentClose",
			pos:  position{line: 133, col: 1, offset: 3261},
			expr: &litMatcher{
				pos:        position{line: 133, col: 23, offset: 3283},
				val:        "*/",
				ignoreCase: false,
				want:       "\"*/\"",
			},
		},
		{
			name: "DelimitedSection",
			pos:  position{line: 135, col: 1, offset: 3291},
			expr: &actionExpr{
				pos: position{line: 135, col: 21, offset: 3311},
				run: (*parser).callonDelimitedSection1,
				expr: &seqExpr{
					pos: position{line: 135, col: 21, offset: 3311},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 135, col: 21, offset: 3311},
							label: "begin",
							expr: &ruleRefExpr{
								pos:  position{line: 135, col: 27, offset: 3317},
								name: "DelimitedSectionBegin",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 135, col: 49, offset: 3339},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 135, col: 51, offset: 3341},
							label: "fields",
							expr: &choiceExpr{
								pos: position{line: 135, col: 59, offset: 3349},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 135, col: 59, offset: 3349},
										name: "AssignmentList",
									},
									&ruleRefExpr{
										pos:  position{line: 135, col: 76, offset: 3366},
										name: "EmptyBody",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 135, col: 87, offset: 3377},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 135, col: 89, offset: 3379},
							name: "DelimitedSectionEnd",
						},
					},
				},
			},
		},
		{
			name: "DelimitedSectionBegin",
			pos:  position{line: 141, col: 1, offset: 3515},
			expr: &actionExpr{
				pos: position{line: 141, col: 26, offset: 3540},
				run: (*parser).callonDelimitedSectionBegin1,
				expr: &seqExpr{
					pos: position{line: 141, col: 26, offset: 3540},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 141, col: 26, offset: 3540},
							val:        "/* Begin ",
							ignoreCase: false,
							want:       "\"/* Begin \"",
						},
						&labeledExpr{
							pos:   position{line: 141, col: 38, offset: 3552},
							label: "sectionName",
							expr: &ruleRefExpr{
								pos:  position{line: 141, col: 50, offset: 3564},
								name: "Identifier",
							},
						},
						&litMatcher{
							pos:        position{line: 141, col: 61, offset: 3575},
							val:        " section */",
							ignoreCase: false,
							want:       "\" section */\"",
						},
						&ruleRefExpr{
							pos:  position{line: 141, col: 75, offset: 3589},
							name: "NewLine",
						},
					},
				},
			},
		},
		{
			name: "DelimitedSectionEnd",
			pos:  position{line: 147, col: 1, offset: 3690},
			expr: &actionExpr{
				pos: position{line: 147, col: 24, offset: 3713},
				run: (*parser).callonDelimitedSectionEnd1,
				expr: &seqExpr{
					pos: position{line: 147, col: 24, offset: 3713},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 147, col: 24, offset: 3713},
							val:        "/* End ",
							ignoreCase: false,
							want:       "\"/* End \"",
						},
						&labeledExpr{
							pos:   position{line: 147, col: 34, offset: 3723},
							label: "sectionName",
							expr: &ruleRefExpr{
								pos:  position{line: 147, col: 46, offset: 3735},
								name: "Identifier",
							},
						},
						&litMatcher{
							pos:        position{line: 147, col: 57, offset: 3746},
							val:        " section */",
							ignoreCase: false,
							want:       "\" section */\"",
						},
						&ruleRefExpr{
							pos:  position{line: 147, col: 71, offset: 3760},
							name: "NewLine",
						},
					},
				},
			},
		},
		{
			name: "Array",
			pos:  position{line: 153, col: 1, offset: 3861},
			expr: &actionExpr{
				pos: position{line: 153, col: 10, offset: 3870},
				run: (*parser).callonArray1,
				expr: &seqExpr{
					pos: position{line: 153, col: 10, offset: 3870},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 153, col: 10, offset: 3870},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&labeledExpr{
							pos:   position{line: 153, col: 14, offset: 3874},
							label: "arr",
							expr: &choiceExpr{
								pos: position{line: 153, col: 19, offset: 3879},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 153, col: 19, offset: 3879},
										name: "ArrayBody",
									},
									&ruleRefExpr{
										pos:  position{line: 153, col: 31, offset: 3891},
										name: "EmptyArray",
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 153, col: 44, offset: 3904},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
					},
				},
			},
		},
		{
			name: "EmptyArray",
			pos:  position{line: 157, col: 1, offset: 3937},
			expr: &actionExpr{
				pos: position{line: 157, col: 15, offset: 3951},
				run: (*parser).callonEmptyArray1,
				expr: &ruleRefExpr{
					pos:  position{line: 157, col: 15, offset: 3951},
					name: "_",
				},
			},
		},
		{
			name: "ArrayBody",
			pos:  position{line: 161, col: 1, offset: 4001},
			expr: &actionExpr{
				pos: position{line: 161, col: 14, offset: 4014},
				run: (*parser).callonArrayBody1,
				expr: &seqExpr{
					pos: position{line: 161, col: 14, offset: 4014},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 161, col: 14, offset: 4014},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 161, col: 16, offset: 4016},
							label: "head",
							expr: &ruleRefExpr{
								pos:  position{line: 161, col: 21, offset: 4021},
								name: "ArrayEntry",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 161, col: 32, offset: 4032},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 161, col: 34, offset: 4034},
							label: "tail",
							expr: &zeroOrOneExpr{
								pos: position{line: 161, col: 39, offset: 4039},
								expr: &ruleRefExpr{
									pos:  position{line: 161, col: 39, offset: 4039},
									name: "ArrayBody",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 161, col: 50, offset: 4050},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "ArrayEntry",
			pos:  position{line: 169, col: 1, offset: 4218},
			expr: &choiceExpr{
				pos: position{line: 169, col: 15, offset: 4232},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 169, col: 15, offset: 4232},
						name: "SimpleArrayEntry",
					},
					&ruleRefExpr{
						pos:  position{line: 169, col: 34, offset: 4251},
						name: "CommentedArrayEntry",
					},
				},
			},
		},
		{
			name: "SimpleArrayEntry",
			pos:  position{line: 171, col: 1, offset: 4274},
			expr: &actionExpr{
				pos: position{line: 171, col: 21, offset: 4294},
				run: (*parser).callonSimpleArrayEntry1,
				expr: &seqExpr{
					pos: position{line: 171, col: 21, offset: 4294},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 171, col: 21, offset: 4294},
							label: "val",
							expr: &ruleRefExpr{
								pos:  position{line: 171, col: 25, offset: 4298},
								name: "Value",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 171, col: 31, offset: 4304},
							name: "EndArrayEntry",
						},
					},
				},
			},
		},
		{
			name: "CommentedArrayEntry",
			pos:  position{line: 175, col: 1, offset: 4347},
			expr: &actionExpr{
				pos: position{line: 175, col: 24, offset: 4370},
				run: (*parser).callonCommentedArrayEntry1,
				expr: &seqExpr{
					pos: position{line: 175, col: 24, offset: 4370},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 175, col: 24, offset: 4370},
							label: "val",
							expr: &ruleRefExpr{
								pos:  position{line: 175, col: 28, offset: 4374},
								name: "Value",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 175, col: 34, offset: 4380},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 175, col: 36, offset: 4382},
							label: "comment",
							expr: &ruleRefExpr{
								pos:  position{line: 175, col: 44, offset: 4390},
								name: "InlineComment",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 175, col: 58, offset: 4404},
							name: "EndArrayEntry",
						},
					},
				},
			},
		},
		{
			name: "EndArrayEntry",
			pos:  position{line: 182, col: 1, offset: 4593},
			expr: &choiceExpr{
				pos: position{line: 182, col: 18, offset: 4610},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 182, col: 18, offset: 4610},
						val:        ",",
						ignoreCase: false,
						want:       "\",\"",
					},
					&seqExpr{
						pos: position{line: 182, col: 24, offset: 4616},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 182, col: 24, offset: 4616},
								name: "_",
							},
							&andExpr{
								pos: position{line: 182, col: 26, offset: 4618},
								expr: &litMatcher{
									pos:        position{line: 182, col: 27, offset: 4619},
									val:        ")",
									ignoreCase: false,
									want:       "\")\"",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Identifier",
			pos:  position{line: 184, col: 1, offset: 4626},
			expr: &choiceExpr{
				pos: position{line: 184, col: 15, offset: 4640},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 184, col: 15, offset: 4640},
						name: "IdentifierDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 184, col: 33, offset: 4658},
						name: "QuotedString",
					},
				},
			},
		},
		{
			name: "IdentifierDigit",
			pos:  position{line: 186, col: 1, offset: 4674},
			expr: &actionExpr{
				pos: position{line: 186, col: 20, offset: 4693},
				run: (*parser).callonIdentifierDigit1,
				expr: &labeledExpr{
					pos:   position{line: 186, col: 20, offset: 4693},
					label: "id",
					expr: &oneOrMoreExpr{
						pos: position{line: 186, col: 23, offset: 4696},
						expr: &charClassMatcher{
							pos:        position{line: 186, col: 23, offset: 4696},
							val:        "[A-Za-z0-9_.]",
							chars:      []rune{'_', '.'},
							ranges:     []rune{'A', 'Z', 'a', 'z', '0', '9'},
							ignoreCase: false,
							inverted:   false,
						},
					},
				},
			},
		},
		{
			name: "Value",
			pos:  position{line: 190, col: 1, offset: 4754},
			expr: &choiceExpr{
				pos: position{line: 190, col: 10, offset: 4763},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 190, col: 10, offset: 4763},
						name: "Object",
					},
					&ruleRefExpr{
						pos:  position{line: 190, col: 19, offset: 4772},
						name: "Array",
					},
					&ruleRefExpr{
						pos:  position{line: 190, col: 27, offset: 4780},
						name: "NumberValue",
					},
					&ruleRefExpr{
						pos:  position{line: 190, col: 41, offset: 4794},
						name: "StringValue",
					},
				},
			},
		},
		{
			name: "NumberValue",
			pos:  position{line: 192, col: 1, offset: 4809},
			expr: &choiceExpr{
				pos: position{line: 192, col: 16, offset: 4824},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 192, col: 16, offset: 4824},
						name: "DecimalValue",
					},
					&ruleRefExpr{
						pos:  position{line: 192, col: 31, offset: 4839},
						name: "IntegerValue",
					},
				},
			},
		},
		{
			name: "DecimalValue",
			pos:  position{line: 194, col: 1, offset: 4855},
			expr: &actionExpr{
				pos: position{line: 194, col: 17, offset: 4871},
				run: (*parser).callonDecimalValue1,
				expr: &labeledExpr{
					pos:   position{line: 194, col: 17, offset: 4871},
					label: "decimal",
					expr: &seqExpr{
						pos: position{line: 194, col: 26, offset: 4880},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 194, col: 26, offset: 4880},
								name: "IntegerValue",
							},
							&litMatcher{
								pos:        position{line: 194, col: 39, offset: 4893},
								val:        ".",
								ignoreCase: false,
								want:       "\".\"",
							},
							&ruleRefExpr{
								pos:  position{line: 194, col: 43, offset: 4897},
								name: "IntegerValue",
							},
						},
					},
				},
			},
		},
		{
			name: "IntegerValue",
			pos:  position{line: 198, col: 1, offset: 4978},
			expr: &actionExpr{
				pos: position{line: 198, col: 17, offset: 4994},
				run: (*parser).callonIntegerValue1,
				expr: &seqExpr{
					pos: position{line: 198, col: 17, offset: 4994},
					exprs: []interface{}{
						&notExpr{
							pos: position{line: 198, col: 17, offset: 4994},
							expr: &ruleRefExpr{
								pos:  position{line: 198, col: 18, offset: 4995},
								name: "Alpha",
							},
						},
						&labeledExpr{
							pos:   position{line: 198, col: 24, offset: 5001},
							label: "number",
							expr: &oneOrMoreExpr{
								pos: position{line: 198, col: 31, offset: 5008},
								expr: &ruleRefExpr{
									pos:  position{line: 198, col: 31, offset: 5008},
									name: "Digit",
								},
							},
						},
						&notExpr{
							pos: position{line: 198, col: 38, offset: 5015},
							expr: &ruleRefExpr{
								pos:  position{line: 198, col: 39, offset: 5016},
								name: "NonTerminator",
							},
						},
					},
				},
			},
		},
		{
			name: "StringValue",
			pos:  position{line: 202, col: 1, offset: 5098},
			expr: &choiceExpr{
				pos: position{line: 202, col: 16, offset: 5113},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 202, col: 16, offset: 5113},
						name: "QuotedString",
					},
					&ruleRefExpr{
						pos:  position{line: 202, col: 31, offset: 5128},
						name: "LiteralString",
					},
				},
			},
		},
		{
			name: "QuotedString",
			pos:  position{line: 204, col: 1, offset: 5145},
			expr: &actionExpr{
				pos: position{line: 204, col: 17, offset: 5161},
				run: (*parser).callonQuotedString1,
				expr: &seqExpr{
					pos: position{line: 204, col: 17, offset: 5161},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 204, col: 17, offset: 5161},
							name: "DoubleQuote",
						},
						&labeledExpr{
							pos:   position{line: 204, col: 29, offset: 5173},
							label: "str",
							expr: &ruleRefExpr{
								pos:  position{line: 204, col: 33, offset: 5177},
								name: "QuotedBody",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 204, col: 44, offset: 5188},
							name: "DoubleQuote",
						},
					},
				},
			},
		},
		{
			name: "QuotedBody",
			pos:  position{line: 208, col: 1, offset: 5252},
			expr: &actionExpr{
				pos: position{line: 208, col: 15, offset: 5266},
				run: (*parser).callonQuotedBody1,
				expr: &labeledExpr{
					pos:   position{line: 208, col: 15, offset: 5266},
					label: "str",
					expr: &oneOrMoreExpr{
						pos: position{line: 208, col: 19, offset: 5270},
						expr: &ruleRefExpr{
							pos:  position{line: 208, col: 19, offset: 5270},
							name: "NonQuote",
						},
					},
				},
			},
		},
		{
			name: "NonQuote",
			pos:  position{line: 212, col: 1, offset: 5324},
			expr: &choiceExpr{
				pos: position{line: 212, col: 13, offset: 5336},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 212, col: 13, offset: 5336},
						name: "EscapedQuote",
					},
					&actionExpr{
						pos: position{line: 212, col: 28, offset: 5351},
						run: (*parser).callonNonQuote3,
						expr: &seqExpr{
							pos: position{line: 212, col: 28, offset: 5351},
							exprs: []interface{}{
								&notExpr{
									pos: position{line: 212, col: 28, offset: 5351},
									expr: &ruleRefExpr{
										pos:  position{line: 212, col: 29, offset: 5352},
										name: "DoubleQuote",
									},
								},
								&labeledExpr{
									pos:   position{line: 212, col: 41, offset: 5364},
									label: "char",
									expr: &anyMatcher{
										line: 212, col: 46, offset: 5369,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "EscapedQuote",
			pos:  position{line: 216, col: 1, offset: 5401},
			expr: &actionExpr{
				pos: position{line: 216, col: 17, offset: 5417},
				run: (*parser).callonEscapedQuote1,
				expr: &seqExpr{
					pos: position{line: 216, col: 17, offset: 5417},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 216, col: 17, offset: 5417},
							val:        "\\",
							ignoreCase: false,
							want:       "\"\\\\\"",
						},
						&ruleRefExpr{
							pos:  position{line: 216, col: 22, offset: 5422},
							name: "DoubleQuote",
						},
					},
				},
			},
		},
		{
			name: "LiteralString",
			pos:  position{line: 220, col: 1, offset: 5466},
			expr: &actionExpr{
				pos: position{line: 220, col: 18, offset: 5483},
				run: (*parser).callonLiteralString1,
				expr: &labeledExpr{
					pos:   position{line: 220, col: 18, offset: 5483},
					label: "literal",
					expr: &oneOrMoreExpr{
						pos: position{line: 220, col: 26, offset: 5491},
						expr: &ruleRefExpr{
							pos:  position{line: 220, col: 26, offset: 5491},
							name: "LiteralChar",
						},
					},
				},
			},
		},
		{
			name: "LiteralChar",
			pos:  position{line: 224, col: 1, offset: 5552},
			expr: &actionExpr{
				pos: position{line: 224, col: 16, offset: 5567},
				run: (*parser).callonLiteralChar1,
				expr: &seqExpr{
					pos: position{line: 224, col: 16, offset: 5567},
					exprs: []interface{}{
						&notExpr{
							pos: position{line: 224, col: 16, offset: 5567},
							expr: &ruleRefExpr{
								pos:  position{line: 224, col: 17, offset: 5568},
								name: "InlineCommentOpen",
							},
						},
						&notExpr{
							pos: position{line: 224, col: 35, offset: 5586},
							expr: &ruleRefExpr{
								pos:  position{line: 224, col: 36, offset: 5587},
								name: "LineTerminator",
							},
						},
						&labeledExpr{
							pos:   position{line: 224, col: 51, offset: 5602},
							label: "char",
							expr: &ruleRefExpr{
								pos:  position{line: 224, col: 56, offset: 5607},
								name: "NonTerminator",
							},
						},
					},
				},
			},
		},
		{
			name: "NonTerminator",
			pos:  position{line: 228, col: 1, offset: 5651},
			expr: &charClassMatcher{
				pos:        position{line: 228, col: 18, offset: 5668},
				val:        "[^;,\\n]",
				chars:      []rune{';', ',', '\n'},
				ignoreCase: false,
				inverted:   true,
			},
		},
		{
			name: "SingleLineComment",
			pos:  position{line: 230, col: 1, offset: 5679},
			expr: &actionExpr{
				pos: position{line: 230, col: 22, offset: 5700},
				run: (*parser).callonSingleLineComment1,
				expr: &seqExpr{
					pos: position{line: 230, col: 22, offset: 5700},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 230, col: 22, offset: 5700},
							val:        "//",
							ignoreCase: false,
							want:       "\"//\"",
						},
						&ruleRefExpr{
							pos:  position{line: 230, col: 27, offset: 5705},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 230, col: 29, offset: 5707},
							label: "contents",
							expr: &ruleRefExpr{
								pos:  position{line: 230, col: 38, offset: 5716},
								name: "OneLineString",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 230, col: 52, offset: 5730},
							name: "NewLine",
						},
					},
				},
			},
		},
		{
			name: "OneLineString",
			pos:  position{line: 234, col: 1, offset: 5772},
			expr: &actionExpr{
				pos: position{line: 234, col: 18, offset: 5789},
				run: (*parser).callonOneLineString1,
				expr: &labeledExpr{
					pos:   position{line: 234, col: 18, offset: 5789},
					label: "content",
					expr: &zeroOrMoreExpr{
						pos: position{line: 234, col: 26, offset: 5797},
						expr: &ruleRefExpr{
							pos:  position{line: 234, col: 26, offset: 5797},
							name: "NonLine",
						},
					},
				},
			},
		},
		{
			name: "Digit",
			pos:  position{line: 238, col: 1, offset: 5839},
			expr: &charClassMatcher{
				pos:        position{line: 238, col: 10, offset: 5848},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "Alpha",
			pos:  position{line: 240, col: 1, offset: 5857},
			expr: &charClassMatcher{
				pos:        position{line: 240, col: 10, offset: 5866},
				val:        "[a-zA-Z]",
				ranges:     []rune{'a', 'z', 'A', 'Z'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "DoubleQuote",
			pos:  position{line: 242, col: 1, offset: 5878},
			expr: &litMatcher{
				pos:        position{line: 242, col: 16, offset: 5893},
				val:        "\"",
				ignoreCase: false,
				want:       "\"\\\"\"",
			},
		},
		{
			name:        "_",
			displayName: "\"whitespace\"",
			pos:         position{line: 244, col: 1, offset: 5900},
			expr: &zeroOrMoreExpr{
				pos: position{line: 244, col: 19, offset: 5918},
				expr: &ruleRefExpr{
					pos:  position{line: 244, col: 19, offset: 5918},
					name: "whitespace",
				},
			},
		},
		{
			name: "whitespace",
			pos:  position{line: 246, col: 1, offset: 5933},
			expr: &choiceExpr{
				pos: position{line: 246, col: 15, offset: 5947},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 246, col: 15, offset: 5947},
						name: "NewLine",
					},
					&charClassMatcher{
						pos:        position{line: 246, col: 25, offset: 5957},
						val:        "[\\t ]",
						chars:      []rune{'\t', ' '},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "NonLine",
			pos:  position{line: 248, col: 1, offset: 5966},
			expr: &actionExpr{
				pos: position{line: 248, col: 12, offset: 5977},
				run: (*parser).callonNonLine1,
				expr: &seqExpr{
					pos: position{line: 248, col: 12, offset: 5977},
					exprs: []interface{}{
						&notExpr{
							pos: position{line: 248, col: 12, offset: 5977},
							expr: &ruleRefExpr{
								pos:  position{line: 248, col: 13, offset: 5978},
								name: "NewLine",
							},
						},
						&labeledExpr{
							pos:   position{line: 248, col: 21, offset: 5986},
							label: "char",
							expr: &ruleRefExpr{
								pos:  position{line: 248, col: 26, offset: 5991},
								name: "Char",
							},
						},
					},
				},
			},
		},
		{
			name: "LineTerminator",
			pos:  position{line: 252, col: 1, offset: 6026},
			expr: &choiceExpr{
				pos: position{line: 252, col: 19, offset: 6044},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 252, col: 19, offset: 6044},
						name: "NewLine",
					},
					&litMatcher{
						pos:        position{line: 252, col: 29, offset: 6054},
						val:        ";",
						ignoreCase: false,
						want:       "\";\"",
					},
				},
			},
		},
		{
			name: "NewLine",
			pos:  position{line: 254, col: 1, offset: 6061},
			expr: &charClassMatcher{
				pos:        position{line: 254, col: 12, offset: 6072},
				val:        "[\\n\\r]",
				chars:      []rune{'\n', '\r'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "Char",
			pos:  position{line: 256, col: 1, offset: 6082},
			expr: &anyMatcher{
				line: 256, col: 9, offset: 6090,
			},
		},
		{
			name: "EOF",
			pos:  position{line: 258, col: 1, offset: 6095},
			expr: &notExpr{
				pos: position{line: 258, col: 8, offset: 6102},
				expr: &anyMatcher{
					line: 258, col: 9, offset: 6103,
				},
			},
		},
	},
}

func (c *current) onProject1(headComment, obj interface{}) (interface{}, error) {

	proj := newObject()
	proj["project"] = obj

	if headComment != nil {
		proj["headComment"] = charsToString(headComment)
	}

	return proj, nil
}

func (p *parser) callonProject1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onProject1(stack["headComment"], stack["obj"])
}

func (c *current) onObject1(obj interface{}) (interface{}, error) {

	return obj, nil
}

func (p *parser) callonObject1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onObject1(stack["obj"])
}

func (c *current) onEmptyBody1() (interface{}, error) {

	return newObject(), nil
}

func (p *parser) callonEmptyBody1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEmptyBody1()
}

func (c *current) onAssignmentList1(_list interface{}) (interface{}, error) {

	list := _list.([]interface{})
	returnObject := list[0].([]interface{})[0].(Object)
	for _, v := range list {
		another := v.([]interface{})[0].(Object)
		returnObject = merge_obj(returnObject, another)
	}

	return returnObject, nil
}

func (p *parser) callonAssignmentList1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAssignmentList1(stack["_list"])
}

func (c *current) onSimpleAssignment1(id, val interface{}) (interface{}, error) {

	result := newObject()
	result[id.(string)] = val
	return result, nil
}

func (p *parser) callonSimpleAssignment1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSimpleAssignment1(stack["id"], stack["val"])
}

func (c *current) onCommentedAssignment11(commentedId, val interface{}) (interface{}, error) {

	result := newObject()
	commentKey := (commentedId.(Object)["id"]).(string) + "_comment"

	result[commentedId.(Object)["id"].(string)] = val
	result[commentKey] = commentedId.(Object)[commentKey]
	return result, nil
}

func (p *parser) callonCommentedAssignment11() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCommentedAssignment11(stack["commentedId"], stack["val"])
}

func (c *current) onCommentedAssignment21(id, commentedVal interface{}) (interface{}, error) {

	result := newObject()
	result[id.(string)] = commentedVal.(Object)["value"]
	result[id.(string)+"_comment"] = commentedVal.(Object)["comment"]
	return result, nil
}

func (p *parser) callonCommentedAssignment21() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCommentedAssignment21(stack["id"], stack["commentedVal"])
}

func (c *current) onCommentedIdentifier1(id, comment interface{}) (interface{}, error) {

	result := newObject()
	result["id"] = id
	result[id.(string)+"_comment"] = strings.TrimSpace(comment.(string))
	return result, nil
}

func (p *parser) callonCommentedIdentifier1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCommentedIdentifier1(stack["id"], stack["comment"])
}

func (c *current) onCommentedValue1(literal, comment interface{}) (interface{}, error) {

	result := newObject()
	result["comment"] = strings.TrimSpace(comment.(string))
	result["value"] = strings.TrimSpace(literal.(string))
	return result, nil
}

func (p *parser) callonCommentedValue1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCommentedValue1(stack["literal"], stack["comment"])
}

func (c *current) onInlineComment1(body interface{}) (interface{}, error) {

	return charsToString(body), nil
}

func (p *parser) callonInlineComment1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInlineComment1(stack["body"])
}

func (c *current) onDelimitedSection1(begin, fields interface{}) (interface{}, error) {

	section := newObject()
	section[begin.(Object)["name"].(string)] = fields
	return section, nil
}

func (p *parser) callonDelimitedSection1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDelimitedSection1(stack["begin"], stack["fields"])
}

func (c *current) onDelimitedSectionBegin1(sectionName interface{}) (interface{}, error) {

	result := newObject()
	result["name"] = sectionName
	return result, nil
}

func (p *parser) callonDelimitedSectionBegin1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDelimitedSectionBegin1(stack["sectionName"])
}

func (c *current) onDelimitedSectionEnd1(sectionName interface{}) (interface{}, error) {

	result := newObject()
	result["name"] = sectionName
	return result, nil
}

func (p *parser) callonDelimitedSectionEnd1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDelimitedSectionEnd1(stack["sectionName"])
}

func (c *current) onArray1(arr interface{}) (interface{}, error) {

	return arr, nil
}

func (p *parser) callonArray1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onArray1(stack["arr"])
}

func (c *current) onEmptyArray1() (interface{}, error) {

	return make([]interface{}, 0), nil
}

func (p *parser) callonEmptyArray1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEmptyArray1()
}

func (c *current) onArrayBody1(head, tail interface{}) (interface{}, error) {

	if tail != nil {
		return append([]interface{}{head}, tail.([]interface{})...), nil
	} else {
		return []interface{}{head}, nil
	}
}

func (p *parser) callonArrayBody1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onArrayBody1(stack["head"], stack["tail"])
}

func (c *current) onSimpleArrayEntry1(val interface{}) (interface{}, error) {

	return val, nil
}

func (p *parser) callonSimpleArrayEntry1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSimpleArrayEntry1(stack["val"])
}

func (c *current) onCommentedArrayEntry1(val, comment interface{}) (interface{}, error) {

	result := newObject()
	result["value"] = strings.TrimSpace(val.(string))
	result["comment"] = strings.TrimSpace(comment.(string))
	return result, nil
}

func (p *parser) callonCommentedArrayEntry1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCommentedArrayEntry1(stack["val"], stack["comment"])
}

func (c *current) onIdentifierDigit1(id interface{}) (interface{}, error) {

	return charsToString(id), nil
}

func (p *parser) callonIdentifierDigit1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdentifierDigit1(stack["id"])
}

func (c *current) onDecimalValue1(decimal interface{}) (interface{}, error) {

	return strconv.ParseFloat(charsToString(decimal), 32)
}

func (p *parser) callonDecimalValue1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDecimalValue1(stack["decimal"])
}

func (c *current) onIntegerValue1(number interface{}) (interface{}, error) {

	return strconv.ParseInt(charsToString(number), 10, 32)
}

func (p *parser) callonIntegerValue1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIntegerValue1(stack["number"])
}

func (c *current) onQuotedString1(str interface{}) (interface{}, error) {

	return "\"" + str.(string) + "\"", nil
}

func (p *parser) callonQuotedString1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onQuotedString1(stack["str"])
}

func (c *current) onQuotedBody1(str interface{}) (interface{}, error) {

	return charsToString(str), nil
}

func (p *parser) callonQuotedBody1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onQuotedBody1(stack["str"])
}

func (c *current) onNonQuote3(char interface{}) (interface{}, error) {

	return char, nil
}

func (p *parser) callonNonQuote3() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNonQuote3(stack["char"])
}

func (c *current) onEscapedQuote1() (interface{}, error) {

	return "\\\"", nil
}

func (p *parser) callonEscapedQuote1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEscapedQuote1()
}

func (c *current) onLiteralString1(literal interface{}) (interface{}, error) {

	return charsToString(literal), nil
}

func (p *parser) callonLiteralString1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLiteralString1(stack["literal"])
}

func (c *current) onLiteralChar1(char interface{}) (interface{}, error) {

	return char, nil
}

func (p *parser) callonLiteralChar1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLiteralChar1(stack["char"])
}

func (c *current) onSingleLineComment1(contents interface{}) (interface{}, error) {

	return contents, nil
}

func (p *parser) callonSingleLineComment1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSingleLineComment1(stack["contents"])
}

func (c *current) onOneLineString1(content interface{}) (interface{}, error) {

	return content, nil
}

func (p *parser) callonOneLineString1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOneLineString1(stack["content"])
}

func (c *current) onNonLine1(char interface{}) (interface{}, error) {

	return char, nil
}

func (p *parser) callonNonLine1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNonLine1(stack["char"])
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//     input := "input"
//     stats := Stats{}
//     _, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//     if err != nil {
//         log.Panicln(err)
//     }
//     b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//     if err != nil {
//         log.Panicln(err)
//     }
//     fmt.Println(string(b))
//
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i interface{}, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]interface{}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type recoveryExpr struct {
	pos          position
	expr         interface{}
	recoverExpr  interface{}
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]interface{}
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr interface{}) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]interface{}, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() interface{}
}

var statePool = &sync.Pool{
	New: func() interface{} { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRule(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val interface{}
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExpr(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExpr(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]interface{}, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExpr(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
